// Model fit grading — a FIXTURE-VERIFIED COPY of the website's
// lib/checker-engine.js, same arrangement as derive/bands.js.
//
// WHY A COPY (discovery-spec §8 decision 4)
// Phase 0/1 share the engine as a fixture-verified copy rather than an
// extracted package — the approach the mobile app already proved. This
// repository never imports from the website; `fixtures/website-engine-parity.json`
// was GENERATED by executing the website's engine, and test/fit.test.js pins
// every value against it. If the website changes a threshold, that test fails
// and the fixture is re-pinned in a deliberate commit.
//
// WHAT IS DELIBERATELY NOT COPIED
// `scoreModel` and its 0–100 weighting. This dashboard reports what fits and
// what it costs; it does not rank models for you. A composite score would be an
// opinion dressed as a measurement, and the weights behind it are only
// defensible on the website, where the surrounding copy explains them.

// Effective bits-per-weight per quant (llama.cpp quantize table / community
// measured file sizes). K-quants carry per-block scale/min metadata above their
// nominal bit width, which is why these are not round numbers.
const EFFECTIVE_BITS = {
  fp32: 32,
  fp16: 16,
  bf16: 16,
  q8_0: 8.5,
  q6_k: 6.56,
  q5_k_m: 5.69,
  q4_k_m: 4.85,
  q4_k_s: 4.58,
  q3_k_m: 3.91,
  q2_k: 2.5,
  iq4_xs: 4.25,
  iq4_nl: 4.5,
  iq3_xs: 3.4,
  iq2_xs: 2.31,
};

/** Activations + runtime bookkeeping + ~1 GB headroom. */
export const RUNTIME_OVERHEAD_GB = 1.5;
export const COMFORTABLE_HEADROOM_GB = 2;
/** RAM offload needs ~1.6x to cover split CPU/GPU overhead. */
export const RAM_OFFLOAD_MULTIPLIER = 1.6;

export const FIT_GRADES = ["comfortable", "tight", "partial", "too_large"];

export function estimateWeightVram(paramsBillions, effectiveBits) {
  return (paramsBillions * effectiveBits) / 8;
}

export function estimateTotalVram(paramsBillions, quantKey) {
  const bits = EFFECTIVE_BITS[quantKey] ?? EFFECTIVE_BITS.q4_k_m;
  return estimateWeightVram(paramsBillions, bits) + RUNTIME_OVERHEAD_GB;
}

export function gradeVramFit(vramGb, requiredVramGb, systemRamGb = 0) {
  if (vramGb > 0) {
    if (vramGb >= requiredVramGb + COMFORTABLE_HEADROOM_GB) return "comfortable";
    if (vramGb >= requiredVramGb) return "tight";
  }
  if (systemRamGb >= requiredVramGb * RAM_OFFLOAD_MULTIPLIER) return "partial";
  return "too_large";
}

export function pickBestQuantization(model, vramGb, systemRamGb = 0) {
  const { q4_k_m, q8_0, fp16 } = model.quantizations ?? {};
  if (vramGb > 0) {
    if (fp16 && vramGb >= fp16.vramGb) return "fp16";
    if (q8_0 && vramGb >= q8_0.vramGb) return "q8_0";
    if (q4_k_m && vramGb >= q4_k_m.vramGb) return "q4_k_m";
  }
  if (q4_k_m && systemRamGb >= q4_k_m.vramGb * RAM_OFFLOAD_MULTIPLIER) return "q4_k_m";
  return null;
}

/**
 * A sparse mixture-of-experts model moves only its active experts per token, so
 * it stays genuinely usable when offloaded — where a dense model pays for every
 * weight per token and drops to 1–5 tok/s. Both were measured on the RTX 3080:
 * sparse MoE held 30–33 tok/s at ~40% residency, dense managed 2.4–3.1.
 *
 * Fit grading itself stays total-parameter; this changes explanation only.
 */
export function isSparseMoe(model) {
  const active = model.activeParametersBillions;
  return Number.isFinite(active) && active > 0 && active < model.parametersBillions;
}

/**
 * Plain-language explanation of a fit result. Deliberately states the cost of a
 * partial fit rather than presenting it as a pass — "it runs" and "it is usable"
 * are different claims, and conflating them is how a recommendation surface
 * loses trust.
 */
export function explainFit({ model, quant, fit, vramGb }) {
  if (!quant || fit === "too_large") {
    const minNeeded =
      model.quantizations?.q4_k_m?.vramGb ?? model.quantizations?.q8_0?.vramGb ?? 0;
    return `Needs about ${minNeeded} GB of VRAM, or roughly ${Math.ceil(minNeeded * RAM_OFFLOAD_MULTIPLIER)} GB of system RAM to run on CPU. This machine has neither.`;
  }

  const required = model.quantizations[quant].vramGb;
  const quantLabel = { fp16: "FP16", q8_0: "Q8_0", q4_k_m: "Q4_K_M" }[quant] ?? quant;

  if (fit === "comfortable") {
    const headroom = Math.round((vramGb - required) * 10) / 10;
    return `Fits in ${quantLabel} with ${headroom} GB of VRAM to spare.`;
  }
  if (fit === "tight") {
    return `Fills nearly all ${vramGb} GB of VRAM in ${quantLabel}. Close long-context sessions you are not using.`;
  }
  if (isSparseMoe(model)) {
    return `Runs via CPU RAM offload in ${quantLabel} at usable speed — it is a sparse mixture-of-experts model and activates only about ${model.activeParametersBillions}B of its ${model.parametersBillions}B parameters per token.`;
  }
  return `Runs via CPU RAM offload in ${quantLabel}, but expect roughly 1–5 tokens per second.`;
}

/**
 * Quant-variant tags are NOT derivable from the base tag (`llama3:8b` needs
 * `llama3:8b-instruct-q8_0`; `phi4` needs `phi4:14b-q8_0`), so a command renders
 * only when the catalog carries an explicit registry-verified tag. Never
 * synthesize one — fabricated tags are a defect class the website's integrity
 * gate exists to catch, and a copy-pasteable command that 404s is worse than
 * no command at all.
 */
export function ollamaRunCommand(model, quant) {
  if (!model.ollamaTag) return null;
  if (quant === "fp16") return model.ollamaTagFp16 ? `ollama run ${model.ollamaTagFp16}` : null;
  if (quant === "q8_0") return model.ollamaTagQ8 ? `ollama run ${model.ollamaTagQ8}` : null;
  return `ollama run ${model.ollamaTag}`;
}

/**
 * Grade one catalog model against this machine.
 *
 * @param {object} model    A catalog entry.
 * @param {object} hardware {vramGb, systemRamGb} — already resolved by the
 *   caller, which is where the Apple usable-memory and nameplate-rounding rules
 *   are applied. This function does no unit reasoning of its own.
 */
export function gradeModel(model, { vramGb = 0, systemRamGb = 0 } = {}) {
  const quant = pickBestQuantization(model, vramGb, systemRamGb);
  const requiredVramGb = quant ? model.quantizations[quant].vramGb : null;
  const fit = quant ? gradeVramFit(vramGb, requiredVramGb, systemRamGb) : "too_large";

  return {
    id: model.id,
    name: model.name,
    parametersBillions: model.parametersBillions,
    activeParametersBillions: model.activeParametersBillions ?? null,
    sparseMoe: isSparseMoe(model),
    contextWindowTokens: model.contextWindowTokens ?? null,
    license: model.license ?? null,
    quant,
    requiredVramGb,
    fit,
    explanation: explainFit({ model, quant, fit, vramGb }),
    // A command is offered to COPY, never to run. Phase 1 is read-only.
    runCommand: quant ? ollamaRunCommand(model, quant) : null,
    ollamaTag: model.ollamaTag ?? null,
  };
}

const FIT_ORDER = { comfortable: 0, tight: 1, partial: 2, too_large: 3 };

/**
 * Grade a catalog against this machine.
 *
 * Ordering is by fit then by size descending — NOT by a quality score. The
 * dashboard's job is to say what runs here and what it costs; picking a
 * "best" model is the website's job, where the reasoning is visible.
 */
export function gradeCatalog(models, hardware) {
  return models
    .map((model) => gradeModel(model, hardware))
    .sort((a, b) => {
      const byFit = FIT_ORDER[a.fit] - FIT_ORDER[b.fit];
      if (byFit !== 0) return byFit;
      return (b.parametersBillions ?? 0) - (a.parametersBillions ?? 0);
    });
}
