import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  ENVIRONMENT_DECLARATION_SOURCE,
  OLLAMA_ENVIRONMENT_VARIABLES,
  compareRuntimeEnvironments,
  deriveRuntimeEnvironment,
  environmentDeclarationHash,
} from "../src/derive/environment.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = async (...p) => JSON.parse(await readFile(path.join(root, ...p), "utf8"));

const ENVIRONMENT_COPY = path.join("src", "derive", "bench-environment.generated.js");
const VERBATIM_MARKER = "// @generated:begin-verbatim\n";
/** Must match the sync script exactly — see sync-from-bench.mjs on why LF-normalized. */
const normalizeEol = (text) => text.replace(/\r\n/g, "\n");

// THE PRIMARY PIN — same arrangement as the checker engine: the module is
// copied verbatim, so the copy is checked COMPLETELY by digest rather than at
// sampled points. This is what fails if somebody edits the generated file by
// hand instead of re-running the sync.
test("the generated environment module is bench's file, unedited", async () => {
  const fixture = await load("fixtures", "bench-environment-parity.json");
  const copy = normalizeEol(await readFile(path.join(root, ENVIRONMENT_COPY), "utf8"));

  assert.match(copy, /GENERATED FILE — DO NOT EDIT/, "the copy must announce what it is");

  const at = copy.indexOf(VERBATIM_MARKER);
  assert.notEqual(at, -1, "the verbatim marker must be present to split header from body");
  const body = copy.slice(at + VERBATIM_MARKER.length);
  assert.ok(body.length > 0, "a copy with an empty body would hash to a constant");

  assert.equal(
    createHash("sha256").update(body).digest("hex"),
    fixture.generatedCopy.sha256,
    "the environment copy does not match its recorded digest — do not edit it by hand; " +
      "re-run: node scripts/sync-from-bench.mjs ../opensourcesai-bench",
  );
});

// THE FAÇADE SEAM — the fixture was generated by executing BENCH's own module,
// so these assertions prove src/derive/environment.js delegates to the copy
// rather than quietly reimplementing the rules. The digest cannot see that.
test("declarations and verdicts match bench's own module exactly", async () => {
  const fixture = await load("fixtures", "bench-environment-parity.json");

  assert.equal(ENVIRONMENT_DECLARATION_SOURCE, fixture.ENVIRONMENT_DECLARATION_SOURCE);
  assert.equal(OLLAMA_ENVIRONMENT_VARIABLES.length, fixture.variableCount);
  assert.deepEqual(OLLAMA_ENVIRONMENT_VARIABLES.map((v) => v.name), fixture.variableNames);

  // Rebuild every declaration from the same synthetic environments the sync
  // script used, reconstructed here from the fixture's own declared values —
  // except the presence-only variables, which the fixture deliberately cannot
  // carry values for. Those are exercised separately below.
  const ENVIRONMENTS = {
    "empty": {},
    "kv-q8": { OLLAMA_KV_CACHE_TYPE: "q8_0" },
    "kv-f16-flash": { OLLAMA_KV_CACHE_TYPE: "f16", OLLAMA_FLASH_ATTENTION: "true" },
    "models-path-set": { OLLAMA_MODELS: "/somewhere/that/must/not/leak" },
    "models-path-other": { OLLAMA_MODELS: "/a/different/private/path" },
    "empty-string-unsets": { OLLAMA_KV_CACHE_TYPE: "   " },
    "advisory-only": { OLLAMA_KEEP_ALIVE: "24h" },
  };
  const declarations = Object.fromEntries(
    Object.entries(ENVIRONMENTS).map(([name, raw]) => [name, deriveRuntimeEnvironment(raw)]),
  );
  for (const [name, declaration] of Object.entries(declarations)) {
    assert.deepEqual(declaration, fixture.declarations[name], `declaration drifted: ${name}`);
  }

  for (const [key, expected] of Object.entries(fixture.verdicts)) {
    const [a, b] = key.split("|");
    const left = a === "null" ? null : declarations[a];
    const result = compareRuntimeEnvironments(left, declarations[b]);
    assert.equal(result.verdict, expected.verdict, `verdict drifted: ${key}`);
    assert.equal(result.comparable, expected.comparable, `comparable flag drifted: ${key}`);
    assert.equal(result.differences.length, expected.differences, `difference count drifted: ${key}`);
  }
});

// THE §9 PRIVACY PROPERTY, asserted from this side of the boundary: a
// presence-only variable's VALUE must never appear anywhere in a declaration.
test("presence-only variables never carry their value into a declaration", async () => {
  const fixture = await load("fixtures", "bench-environment-parity.json");
  const secretPath = "C:\\Users\\somebody\\private\\models";
  const declaration = deriveRuntimeEnvironment({ OLLAMA_MODELS: secretPath, OLLAMA_HOST: "10.0.0.5:11434" });

  for (const name of fixture.presenceOnlyVariables) {
    assert.equal(typeof declaration.declared[name], "boolean", `${name} must be captured as presence only`);
  }
  const serialized = JSON.stringify(declaration);
  assert.ok(!serialized.includes("somebody"), "a path value leaked into the declaration");
  assert.ok(!serialized.includes("10.0.0.5"), "an address value leaked into the declaration");
});

// THE HASH IS BUILT AROUND ONE EQUIVALENCE, so it is asserted as one: two
// declarations hash equal exactly when bench's own comparison calls them
// comparable. If this ever breaks in either direction, the stored
// environmentHash stops meaning what every consumer assumes it means.
test("hash equality is exactly bench's comparable verdict", () => {
  const cases = [
    {},
    { OLLAMA_KV_CACHE_TYPE: "q8_0" },
    { OLLAMA_KV_CACHE_TYPE: "f16" },
    { OLLAMA_KV_CACHE_TYPE: "q8_0", OLLAMA_FLASH_ATTENTION: "true" },
    { OLLAMA_MODELS: "/path/one" },
    { OLLAMA_MODELS: "/path/two" },
    { OLLAMA_KEEP_ALIVE: "24h" },
    { OLLAMA_KV_CACHE_TYPE: "  " },
  ].map((env) => deriveRuntimeEnvironment(env));

  for (const a of cases) {
    for (const b of cases) {
      const sameHash = environmentDeclarationHash(a) === environmentDeclarationHash(b);
      const comparable = compareRuntimeEnvironments(a, b).verdict === "comparable";
      assert.equal(
        sameHash,
        comparable,
        `hash equivalence diverged from the comparable verdict for ${JSON.stringify([a.declared, b.declared])}`,
      );
    }
  }
});

test("the hash is canonical: key order cannot change it, and garbage gets no hash", () => {
  const declaration = deriveRuntimeEnvironment({ OLLAMA_KV_CACHE_TYPE: "q8_0" });
  const reordered = {
    ...declaration,
    declared: Object.fromEntries(Object.entries(declaration.declared).reverse()),
  };
  assert.equal(
    environmentDeclarationHash(declaration),
    environmentDeclarationHash(reordered),
    "key order is an accident of construction, not meaning",
  );

  // Never a hash of garbage: an unhashable input yields null, because a hash
  // that cannot be traced to a declared block would make two unknown
  // environments look reliably identical.
  assert.equal(environmentDeclarationHash(null), null);
  assert.equal(environmentDeclarationHash({}), null);
  assert.equal(environmentDeclarationHash({ declared: null }), null);
  assert.equal(environmentDeclarationHash({ declared: ["not", "an", "object"] }), null);

  // And the produced hash fits the storage schema's environmentHash field.
  assert.match(environmentDeclarationHash(declaration), /^[0-9a-f]{64}$/);
});
