import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  COMFORTABLE_HEADROOM_GB,
  RAM_OFFLOAD_MULTIPLIER,
  RUNTIME_OVERHEAD_GB,
  estimateTotalVram,
  gradeCatalog,
  gradeModel,
  gradeVramFit,
  isSparseMoe,
  ollamaRunCommand,
  pickBestQuantization,
} from "../src/derive/fit.js";
import { buildReport } from "../src/derive/report.js";
import { resolveGradingHardware } from "../src/serve/routes.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = async (...p) => JSON.parse(await readFile(path.join(root, ...p), "utf8"));

// PARITY GUARD, same arrangement as bands: the fixture was generated by
// executing the website's own engine, so this pins the copy to the real thing
// rather than to someone's recollection of it.
test("fit engine matches the website's engine exactly", async () => {
  const fixture = await load("fixtures", "website-engine-parity.json");

  assert.equal(RUNTIME_OVERHEAD_GB, fixture.RUNTIME_OVERHEAD_GB);
  assert.equal(COMFORTABLE_HEADROOM_GB, fixture.COMFORTABLE_HEADROOM_GB);
  assert.equal(RAM_OFFLOAD_MULTIPLIER, fixture.RAM_OFFLOAD_MULTIPLIER);

  for (const [key, expected] of Object.entries(fixture.gradeVramFit)) {
    const [v, r, ram] = key.split("|").map(Number);
    assert.equal(gradeVramFit(v, r, ram), expected, `gradeVramFit(${key}) drifted`);
  }

  const model = {
    name: "Test 8B",
    parametersBillions: 8,
    quantizations: { q4_k_m: { vramGb: 5.6 }, q8_0: { vramGb: 9.5 }, fp16: { vramGb: 16 } },
    ollamaTag: "test:8b",
    ollamaTagQ8: "test:8b-q8_0",
    ollamaTagFp16: "test:8b-fp16",
  };
  for (const [key, expected] of Object.entries(fixture.pickBestQuantization)) {
    const [v, ram] = key.split("|").map(Number);
    assert.equal(pickBestQuantization(model, v, ram), expected, `pickBestQuantization(${key}) drifted`);
  }
  for (const [key, expected] of Object.entries(fixture.estimateTotalVram)) {
    const [p, q] = key.split("|");
    assert.equal(estimateTotalVram(Number(p), q), expected, `estimateTotalVram(${key}) drifted`);
  }

  assert.equal(ollamaRunCommand(model, "q4_k_m"), fixture.ollamaRunCommand.q4_k_m);
  assert.equal(ollamaRunCommand(model, "q8_0"), fixture.ollamaRunCommand.q8_0);
  assert.equal(ollamaRunCommand(model, "fp16"), fixture.ollamaRunCommand.fp16);

  // A quant variant with no registry-verified tag must yield NO command rather
  // than a synthesized one. A copy-pasteable command that 404s is worse than
  // none, and fabricated tags are a defect class the website gates against.
  const noVariants = { ...model, ollamaTagQ8: undefined, ollamaTagFp16: undefined };
  assert.equal(ollamaRunCommand(noVariants, "q8_0"), fixture.ollamaRunCommand["q8_0|no-variant-tag"]);
  assert.equal(ollamaRunCommand(noVariants, "fp16"), fixture.ollamaRunCommand["fp16|no-variant-tag"]);
});

test("sparse MoE detection requires a valid active-parameter count", () => {
  assert.equal(isSparseMoe({ parametersBillions: 30, activeParametersBillions: 3 }), true);
  assert.equal(isSparseMoe({ parametersBillions: 8 }), false, "absent means dense");
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: 8 }), false);
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: 0 }), false);
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: null }), false);
});

test("a partial fit is explained as a cost, not sold as a pass", () => {
  const dense = {
    id: "d", name: "Dense 30B", parametersBillions: 30,
    quantizations: { q4_k_m: { vramGb: 19 } }, ollamaTag: "dense:30b",
  };
  const sparse = { ...dense, id: "s", name: "Sparse 30B", activeParametersBillions: 3, ollamaTag: "sparse:30b" };

  const denseGrade = gradeModel(dense, { vramGb: 10, systemRamGb: 64 });
  assert.equal(denseGrade.fit, "partial");
  assert.match(denseGrade.explanation, /1–5 tokens per second/, "dense offload must state the speed cost");

  const sparseGrade = gradeModel(sparse, { vramGb: 10, systemRamGb: 64 });
  assert.equal(sparseGrade.fit, "partial");
  assert.match(sparseGrade.explanation, /usable speed/, "sparse offload is genuinely usable");
  assert.match(sparseGrade.explanation, /3B of its 30B/);
});

test("a model that fits nowhere is graded too_large and offers no command", () => {
  const huge = {
    id: "h", name: "Huge 405B", parametersBillions: 405,
    quantizations: { q4_k_m: { vramGb: 240 } }, ollamaTag: "huge:405b",
  };
  const grade = gradeModel(huge, { vramGb: 12, systemRamGb: 32 });
  assert.equal(grade.fit, "too_large");
  assert.equal(grade.quant, null);
  assert.equal(grade.runCommand, null, "never offer a command for something that cannot run");
  assert.match(grade.explanation, /This machine has neither/);
});

test("catalog ordering is by fit then size — never by an invented score", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");
  const graded = gradeCatalog(catalog.models, { vramGb: 12, systemRamGb: 32 });

  const order = { comfortable: 0, tight: 1, partial: 2, too_large: 3 };
  for (let i = 1; i < graded.length; i += 1) {
    const prev = order[graded[i - 1].fit];
    const cur = order[graded[i].fit];
    assert.ok(prev <= cur, "fit ordering must be monotonic");
    if (prev === cur) {
      assert.ok(
        (graded[i - 1].parametersBillions ?? 0) >= (graded[i].parametersBillions ?? 0),
        "within a fit tier, larger models come first",
      );
    }
  }
  assert.equal(graded.some((g) => "score" in g), false, "no composite score may be emitted");
});

// END-TO-END ACROSS THE REAL FIXTURES: the grading basis differs per platform,
// and getting it wrong is the whole class of bug Phase 0 existed to find.
test("each real machine grades against the right memory basis", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");

  const windows = buildReport(await load("fixtures", "windows-rtx-4070-ti.json"));
  const winHw = resolveGradingHardware(windows);
  assert.equal(winHw.basis, "discrete-vram-nameplate");
  assert.equal(winHw.vramGb, 12, "must grade against nameplate 12, not raw 11.99");

  const linux = buildReport(await load("fixtures", "linux-rtx-3080.json"));
  const linuxHw = resolveGradingHardware(linux);
  assert.equal(linuxHw.basis, "discrete-vram-nameplate");
  assert.equal(linuxHw.vramGb, 10);

  const macos = buildReport(await load("fixtures", "macos-m1-8gb.json"));
  const macHw = resolveGradingHardware(macos);
  assert.equal(macHw.basis, "apple-unified-usable");
  assert.equal(macHw.vramGb, 6, "must grade against usable 6 GB, not the 8 GB sticker figure");

  // The consequence, stated as an assertion: the 8 GB Mac must be graded more
  // conservatively than a 10 GB discrete card, which is the entire reason the
  // usable-memory rule exists.
  const macFits = gradeCatalog(catalog.models, macHw).filter((m) => m.fit !== "too_large").length;
  const linuxFits = gradeCatalog(catalog.models, linuxHw).filter((m) => m.fit !== "too_large").length;
  assert.ok(macFits <= linuxFits, "an 8 GB Mac must not be told it runs more than a 10 GB card");
});

test("a machine with no GPU still grades, via RAM offload only", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");
  const graded = gradeCatalog(catalog.models, { vramGb: 0, systemRamGb: 32 });
  assert.ok(graded.length > 0);
  assert.equal(graded.some((g) => g.fit === "comfortable"), false, "no GPU means nothing is comfortable");
  assert.ok(graded.some((g) => g.fit === "partial"), "small models should still be reachable via RAM");
});
