import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  COMFORTABLE_HEADROOM_GB,
  RAM_OFFLOAD_MULTIPLIER,
  RUNTIME_OVERHEAD_GB,
  estimateTotalVram,
  fitRequirementGb,
  gradeCatalog,
  gradeModel,
  gradeModelFit,
  gradeVramFit,
  isSparseMoe,
  ollamaRunCommand,
  pickBestQuantization,
} from "../src/derive/fit.js";
import { buildReport } from "../src/derive/report.js";
import { resolveGradingHardware } from "../src/serve/routes.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = async (...p) => JSON.parse(await readFile(path.join(root, ...p), "utf8"));

const ENGINE_COPY = path.join("src", "derive", "checker-engine.generated.js");
const VERBATIM_MARKER = "// @generated:begin-verbatim\n";
/** Must match the sync script exactly — see the note there on why LF-normalized. */
const normalizeEol = (text) => text.replace(/\r\n/g, "\n");

// THE PRIMARY PIN, and the one that made the parity fixture below stop being the
// last line of defence. The engine is copied verbatim by
// scripts/sync-from-website.mjs, so the copy can be checked *completely* rather
// than at sampled points: hash the bytes below the marker and compare against
// what the script recorded when it copied them.
//
// This is what fails if somebody edits the generated file by hand — the failure
// mode a generated file invites, and the one thing the digest can see that a
// behavioural fixture cannot.
test("the generated engine is the website's file, unedited", async () => {
  const fixture = await load("fixtures", "website-engine-parity.json");
  const copy = normalizeEol(await readFile(path.join(root, ENGINE_COPY), "utf8"));

  assert.match(copy, /GENERATED FILE — DO NOT EDIT/, "the copy must announce what it is");

  const at = copy.indexOf(VERBATIM_MARKER);
  assert.notEqual(at, -1, "the verbatim marker must be present to split header from body");

  const body = copy.slice(at + VERBATIM_MARKER.length);
  assert.ok(body.length > 0, "a copy with an empty body would hash to a constant");

  assert.equal(
    createHash("sha256").update(body).digest("hex"),
    fixture.generatedCopy.sha256,
    "the engine copy does not match its recorded digest — do not edit it by hand; " +
      "re-run: node scripts/sync-from-website.mjs ../opensourcesai.com",
  );
  assert.equal(fixture.generatedCopy.file, ENGINE_COPY.replace(/\\/g, "/"));
});

// PARITY GUARD, same arrangement as bands: the fixture was generated by
// executing the website's own engine.
//
// Its job CHANGED when the engine became a verbatim copy. It no longer has to
// prove the copy matches the original — the digest above does that, and does it
// completely. What it still proves is that the façade in src/derive/fit.js
// delegates to the copy instead of quietly reimplementing a piece of it, which
// is the seam a digest cannot see.
test("fit engine matches the website's engine exactly", async () => {
  const fixture = await load("fixtures", "website-engine-parity.json");

  assert.equal(RUNTIME_OVERHEAD_GB, fixture.RUNTIME_OVERHEAD_GB);
  assert.equal(COMFORTABLE_HEADROOM_GB, fixture.COMFORTABLE_HEADROOM_GB);
  assert.equal(RAM_OFFLOAD_MULTIPLIER, fixture.RAM_OFFLOAD_MULTIPLIER);

  for (const [key, expected] of Object.entries(fixture.gradeVramFit)) {
    const [v, r, ram] = key.split("|").map(Number);
    assert.equal(gradeVramFit(v, r, ram), expected, `gradeVramFit(${key}) drifted`);
  }

  // gradeModelFit takes catalog WEIGHTS where gradeVramFit takes a requirement,
  // and gradeModel calls it — so the composition #520 fixed is pinned directly
  // rather than inferred from its parts.
  for (const [key, expected] of Object.entries(fixture.gradeModelFit)) {
    const [v, w, ram] = key.split("|").map(Number);
    assert.equal(gradeModelFit(v, w, ram), expected, `gradeModelFit(${key}) drifted`);
  }
  for (const [key, expected] of Object.entries(fixture.fitRequirementGb)) {
    // "null" round-trips as the non-numeric passthrough case: a null requirement
    // must stay null rather than becoming a 1.5 GB fit out of nowhere.
    const input = key === "null" ? null : Number(key);
    assert.deepEqual(fitRequirementGb(input), expected, `fitRequirementGb(${key}) drifted`);
  }

  const model = {
    name: "Test 8B",
    parametersBillions: 8,
    quantizations: { q4_k_m: { vramGb: 5.6 }, q8_0: { vramGb: 9.5 }, fp16: { vramGb: 16 } },
    ollamaTag: "test:8b",
    ollamaTagQ8: "test:8b-q8_0",
    ollamaTagFp16: "test:8b-fp16",
  };
  for (const [key, expected] of Object.entries(fixture.pickBestQuantization)) {
    const [v, ram] = key.split("|").map(Number);
    assert.equal(pickBestQuantization(model, v, ram), expected, `pickBestQuantization(${key}) drifted`);
  }
  for (const [key, expected] of Object.entries(fixture.estimateTotalVram)) {
    const [p, q] = key.split("|");
    assert.equal(estimateTotalVram(Number(p), q), expected, `estimateTotalVram(${key}) drifted`);
  }

  assert.equal(ollamaRunCommand(model, "q4_k_m"), fixture.ollamaRunCommand.q4_k_m);
  assert.equal(ollamaRunCommand(model, "q8_0"), fixture.ollamaRunCommand.q8_0);
  assert.equal(ollamaRunCommand(model, "fp16"), fixture.ollamaRunCommand.fp16);

  // A quant variant with no registry-verified tag must yield NO command rather
  // than a synthesized one. A copy-pasteable command that 404s is worse than
  // none, and fabricated tags are a defect class the website gates against.
  const noVariants = { ...model, ollamaTagQ8: undefined, ollamaTagFp16: undefined };
  assert.equal(ollamaRunCommand(noVariants, "q8_0"), fixture.ollamaRunCommand["q8_0|no-variant-tag"]);
  assert.equal(ollamaRunCommand(noVariants, "fp16"), fixture.ollamaRunCommand["fp16|no-variant-tag"]);
});

test("sparse MoE detection requires a valid active-parameter count", () => {
  assert.equal(isSparseMoe({ parametersBillions: 30, activeParametersBillions: 3 }), true);
  assert.equal(isSparseMoe({ parametersBillions: 8 }), false, "absent means dense");
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: 8 }), false);
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: 0 }), false);
  assert.equal(isSparseMoe({ parametersBillions: 8, activeParametersBillions: null }), false);
});

test("a partial fit is explained as a cost, not sold as a pass", () => {
  const dense = {
    id: "d", name: "Dense 30B", parametersBillions: 30,
    quantizations: { q4_k_m: { vramGb: 19 } }, ollamaTag: "dense:30b",
  };
  const sparse = { ...dense, id: "s", name: "Sparse 30B", activeParametersBillions: 3, ollamaTag: "sparse:30b" };

  const denseGrade = gradeModel(dense, { vramGb: 10, systemRamGb: 64 });
  assert.equal(denseGrade.fit, "partial");
  assert.match(denseGrade.explanation, /1–5 tokens per second/, "dense offload must state the speed cost");

  const sparseGrade = gradeModel(sparse, { vramGb: 10, systemRamGb: 64 });
  assert.equal(sparseGrade.fit, "partial");
  assert.match(sparseGrade.explanation, /usable speed/, "sparse offload is genuinely usable");
  assert.match(sparseGrade.explanation, /3B of its 30B/);
});

// THE #520 REGRESSION, ASSERTED WHERE THE DASHBOARD ACTUALLY CONSUMES IT.
//
// This is the test that would have failed during the six hours this package
// graded with the pre-fix rule, and nothing in the suite did. The parity fixture
// could not catch it: it pins the ENGINE's functions, and the engine was right —
// the defect was in how this side composed them, one layer above anything the
// fixture looked at.
//
// The case is chosen to sit in the band where the two compositions disagree.
// 9.5 GB of weights on a 10 GB card: bare weights fit (the old answer, "tight"),
// weights + 1.5 GB of runtime overhead do not (the true answer — it runs by
// offloading to RAM, at a fraction of the speed). Grading that "tight" tells
// someone a model is a snug fit when it will in fact crawl, which is the exact
// class of quiet wrongness this project exists to refuse.
test("fit is graded against weights plus runtime overhead, not bare weights", () => {
  const edge = {
    id: "e", name: "Edge 13B", parametersBillions: 13,
    quantizations: { q4_k_m: { vramGb: 9.5 } }, ollamaTag: "edge:13b",
  };

  const grade = gradeModel(edge, { vramGb: 10, systemRamGb: 32 });

  assert.equal(grade.fit, "partial", "9.5 GB of weights does not fit 10 GB once overhead is charged");
  assert.equal(grade.requiredVramGb, 11, "the reported requirement must include runtime overhead");
  assert.match(grade.explanation, /1–5 tokens per second/, "an offloaded fit must state its cost");

  // Naming the wrong answer as well as the right one, so a future reader can see
  // what this is defending against rather than having to reconstruct it.
  assert.notEqual(
    gradeVramFit(10, edge.quantizations.q4_k_m.vramGb, 32),
    grade.fit,
    "this case must stay in the band where the two compositions disagree, or it guards nothing",
  );
});

// The engine destructures model.quantizations without a guard, because the
// website's catalog-integrity gate guarantees the field. That guard now lives in
// gradeModel rather than in the copy, so the copy can stay byte-exact — which
// means the behaviour it protects has to be asserted on this side of the seam.
test("a catalog entry with no quantizations grades as unrunnable rather than throwing", () => {
  const malformed = { id: "m", name: "Malformed", parametersBillions: 8, ollamaTag: "m:8b" };
  const grade = gradeModel(malformed, { vramGb: 12, systemRamGb: 32 });
  assert.equal(grade.fit, "too_large");
  assert.equal(grade.quant, null);
  assert.equal(grade.runCommand, null, "never offer a command for something that cannot run");
});

test("a model that fits nowhere is graded too_large and offers no command", () => {
  const huge = {
    id: "h", name: "Huge 405B", parametersBillions: 405,
    quantizations: { q4_k_m: { vramGb: 240 } }, ollamaTag: "huge:405b",
  };
  const grade = gradeModel(huge, { vramGb: 12, systemRamGb: 32 });
  assert.equal(grade.fit, "too_large");
  assert.equal(grade.quant, null);
  assert.equal(grade.runCommand, null, "never offer a command for something that cannot run");
  assert.match(grade.explanation, /This machine has neither/);
});

test("catalog ordering is by fit then size — never by an invented score", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");
  const graded = gradeCatalog(catalog.models, { vramGb: 12, systemRamGb: 32 });

  const order = { comfortable: 0, tight: 1, partial: 2, too_large: 3 };
  for (let i = 1; i < graded.length; i += 1) {
    const prev = order[graded[i - 1].fit];
    const cur = order[graded[i].fit];
    assert.ok(prev <= cur, "fit ordering must be monotonic");
    if (prev === cur) {
      assert.ok(
        (graded[i - 1].parametersBillions ?? 0) >= (graded[i].parametersBillions ?? 0),
        "within a fit tier, larger models come first",
      );
    }
  }
  assert.equal(graded.some((g) => "score" in g), false, "no composite score may be emitted");
});

// END-TO-END ACROSS THE REAL FIXTURES: the grading basis differs per platform,
// and getting it wrong is the whole class of bug Phase 0 existed to find.
test("each real machine grades against the right memory basis", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");

  const windows = buildReport(await load("fixtures", "windows-rtx-4070-ti.json"));
  const winHw = resolveGradingHardware(windows);
  assert.equal(winHw.basis, "discrete-vram-nameplate");
  assert.equal(winHw.vramGb, 12, "must grade against nameplate 12, not raw 11.99");

  const linux = buildReport(await load("fixtures", "linux-rtx-3080.json"));
  const linuxHw = resolveGradingHardware(linux);
  assert.equal(linuxHw.basis, "discrete-vram-nameplate");
  assert.equal(linuxHw.vramGb, 10);

  const macos = buildReport(await load("fixtures", "macos-m1-8gb.json"));
  const macHw = resolveGradingHardware(macos);
  assert.equal(macHw.basis, "apple-unified-usable");
  assert.equal(macHw.vramGb, 6, "must grade against usable 6 GB, not the 8 GB sticker figure");

  // The consequence, stated as an assertion: the 8 GB Mac must be graded more
  // conservatively than a 10 GB discrete card, which is the entire reason the
  // usable-memory rule exists.
  const macFits = gradeCatalog(catalog.models, macHw).filter((m) => m.fit !== "too_large").length;
  const linuxFits = gradeCatalog(catalog.models, linuxHw).filter((m) => m.fit !== "too_large").length;
  assert.ok(macFits <= linuxFits, "an 8 GB Mac must not be told it runs more than a 10 GB card");
});

test("a machine with no GPU still grades, via RAM offload only", async () => {
  const catalog = await load("data", "checker-models-snapshot.json");
  const graded = gradeCatalog(catalog.models, { vramGb: 0, systemRamGb: 32 });
  assert.ok(graded.length > 0);
  assert.equal(graded.some((g) => g.fit === "comfortable"), false, "no GPU means nothing is comfortable");
  assert.ok(graded.some((g) => g.fit === "partial"), "small models should still be reachable via RAM");
});
