import { execFileSync } from "node:child_process";
import { readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const input = path.join(root, "src", "serve", "theme.css");
const compiled = path.join(root, "src", "serve", "theme.generated.css");
const moduleFile = path.join(root, "src", "serve", "theme.generated.js");
const cli = path.join(root, "node_modules", "@tailwindcss", "cli", "dist", "index.mjs");

execFileSync(process.execPath, [cli, "-i", input, "-o", compiled, "--minify"], {
  cwd: root,
  stdio: "inherit",
});

const css = readFileSync(compiled, "utf8")
  .replace(/^\/\*![\s\S]*?\*\/\s*/, "")
  .trim() + "\n";
const output = [
  "// GENERATED by Tailwind v4. DO NOT EDIT. Regenerate with: npm run build:theme",
  `export const THEME_CSS = ${JSON.stringify(css)};`,
  "",
].join("\n");

writeFileSync(moduleFile, output, "utf8");
unlinkSync(compiled);
