// The conversation store — the prose half of what this tool may remember.
//
// Deferred from the storage layer's first landing DELIBERATELY: shipping a
// conversations directory before the 2026-08-07 boundary decision would have
// announced the inference surface ahead of the amendment that authorizes it.
// That amendment has landed (MAINTAINING §4b); this module is the deferred
// half, under the same §4a rules as the measurements log.
//
// THE DIVISION OF PROSE AND NUMBERS, restated because it is load-bearing:
// conversation files hold the user's words — that is their purpose, and it is
// exactly why they are the most sensitive thing this package will ever write.
// The measurements log holds counters about those exchanges and NO PROSE, so
// measurement history can outlive deleted conversations. The join between the
// two is the conversation id a measurement record may carry — an opaque token,
// never a title, never an excerpt.
//
// Privacy rules, inherited from §4a and tested:
//   - never read by any collector; never in --capture output; never
//     transmitted. (The claim here was "never exported" until 2026-08-10;
//     export now exists as an EXPLICIT USER ACTION in the browser — the page
//     downloads a markdown file to the user's own disk. No server-side
//     export path exists, and this module gained no new reader for it.)
//   - the LIST endpoint's shape carries no prose (ids, timestamps, model names,
//     counts) — reading a conversation's words requires asking for exactly that
//     conversation.
//
// DELETION, CONTAINED. deleteConversation is the reason ids are validated as
// hard as they are: the only path ever removed is <dir>/conversations/<id>.jsonl
// where <id> has already passed a closed-alphabet pattern, and the resolved
// path is then re-checked to sit inside the conversations directory — belt and
// suspenders, because deletion is the one operation with no undo.

import path from "node:path";
import fsp from "node:fs/promises";
import { appendRecord, readRecords } from "./jsonl.js";

/** Subdirectory of the data dir. Everything this module touches lives here. */
export const CONVERSATIONS_DIR = "conversations";

/**
 * Shape of one conversation file's header and events.
 *
 * v2 (2026-08-10): the header gained `systemPrompt` (string or null) — prose,
 * so it belongs HERE and never near the measurements log. Required at v2
 * (null when unset) and refused at v1, the same each-version-carries-exactly-
 * its-own-shape rule the measurement schema follows; v1 files read on,
 * creates stamp v2.
 */
export const CONVERSATION_SCHEMA_VERSION = 2;
export const SUPPORTED_CONVERSATION_VERSIONS = [1, 2];

/**
 * Conversation ids: lowercase hex, generated by the serve layer (storage is
 * random-free). 8–64 chars, no separators, no dots — an id is a NAME, never a
 * path, and the pattern is what makes that structural.
 */
const ID_PATTERN = /^[a-z0-9]{8,64}$/;

const ISO_8601 = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/;

export function validConversationId(id) {
  return typeof id === "string" && ID_PATTERN.test(id);
}

/**
 * Resolve a conversation file path, refusing anything whose id fails the
 * pattern OR whose resolved path escapes the conversations directory. The
 * second check cannot fire while the first holds — that redundancy is the
 * point, for the module that deletes.
 */
function conversationFile(dir, id) {
  if (!validConversationId(id)) return null;
  const base = path.resolve(dir, CONVERSATIONS_DIR);
  const file = path.resolve(base, `${id}.jsonl`);
  if (!file.startsWith(base + path.sep)) return null;
  return file;
}

/**
 * Create a conversation: its file, with a header line. Caller supplies id,
 * timestamp, model and (optionally) a system prompt — storage stamps nothing
 * (§4a rule 5). The prompt is set at creation and never rewritten: a
 * conversation's replies were shaped by whatever prompt stood when they
 * happened, and editing it afterwards would silently reinterpret them.
 */
export async function createConversation(dir, { id, createdAt, model, systemPrompt = null }) {
  if (!validConversationId(id)) return { ok: false, reason: "invalid conversation id" };
  if (typeof createdAt !== "string" || !ISO_8601.test(createdAt)) {
    return { ok: false, reason: "createdAt must be a caller-supplied ISO-8601 timestamp" };
  }
  if (typeof model !== "string" || model.length === 0 || model.length > 200) {
    return { ok: false, reason: "model must be a non-empty string of at most 200 characters" };
  }
  if (!(systemPrompt === null || (typeof systemPrompt === "string" && systemPrompt.length > 0 && systemPrompt.length <= MAX_TEXT_LENGTH))) {
    return { ok: false, reason: "systemPrompt must be null or bounded non-empty text" };
  }
  const file = conversationFile(dir, id);
  await fsp.mkdir(path.resolve(dir, CONVERSATIONS_DIR), { recursive: true });
  try {
    // wx: creating an id that already exists is refused, never overwritten.
    await fsp.writeFile(
      file,
      `${JSON.stringify({ conversationSchemaVersion: CONVERSATION_SCHEMA_VERSION, id, createdAt, model, systemPrompt })}\n`,
      { flag: "wx" },
    );
  } catch (err) {
    if (err.code === "EEXIST") return { ok: false, reason: "a conversation with that id already exists" };
    return { ok: false, reason: `could not create conversation: ${String(err.message).slice(0, 120)}` };
  }
  return { ok: true, id };
}

/**
 * Append one message event. Two event types exist; anything else is refused —
 * a closed vocabulary here keeps a future reader's interpretation honest.
 *
 *   {type:"user",      at, text}
 *   {type:"assistant", at, text, thinking, model, stopped}
 *
 * Text length is capped generously (a quarter-megabyte) — not as privacy (this
 * file IS the prose store) but as a sanity bound against a runaway stream
 * appending an unbounded line.
 */
const MAX_TEXT_LENGTH = 262_144;

export function validateEvent(event) {
  if (event === null || typeof event !== "object" || Array.isArray(event)) {
    return { ok: false, reason: "event must be an object" };
  }
  if (typeof event.at !== "string" || !ISO_8601.test(event.at)) {
    return { ok: false, reason: "event.at must be a caller-supplied ISO-8601 timestamp" };
  }
  const text = (v) => typeof v === "string" && v.length <= MAX_TEXT_LENGTH;

  if (event.type === "user") {
    const keys = Object.keys(event).sort();
    if (keys.join(",") !== "at,text,type") return { ok: false, reason: "user events carry exactly {type, at, text}" };
    if (!text(event.text) || event.text.length === 0) return { ok: false, reason: "user event text is missing or too long" };
    return { ok: true };
  }
  if (event.type === "assistant") {
    const allowed = new Set(["type", "at", "text", "thinking", "model", "stopped"]);
    for (const key of Object.keys(event)) {
      if (!allowed.has(key)) return { ok: false, reason: `unknown assistant-event field: ${key}` };
    }
    if (!text(event.text)) return { ok: false, reason: "assistant event text is missing or too long" };
    if (!(event.thinking === null || text(event.thinking))) return { ok: false, reason: "thinking must be null or bounded text" };
    if (typeof event.model !== "string" || event.model.length === 0 || event.model.length > 200) {
      return { ok: false, reason: "assistant event must name its model" };
    }
    if (typeof event.stopped !== "boolean") return { ok: false, reason: "stopped must be a boolean" };
    return { ok: true };
  }
  return { ok: false, reason: `unknown event type: ${String(event.type).slice(0, 40)}` };
}

export async function appendEvent(dir, id, event) {
  const file = conversationFile(dir, id);
  if (!file) return { ok: false, reason: "invalid conversation id" };
  const verdict = validateEvent(event);
  if (!verdict.ok) return verdict;
  try {
    await fsp.access(file);
  } catch {
    return { ok: false, reason: "no such conversation" };
  }
  await appendRecord(file, event);
  return { ok: true };
}

/**
 * Read one conversation: header plus events, with the JSONL layer's crash
 * honesty carried through (a torn tail is reported, not hidden).
 */
export async function readConversation(dir, id) {
  const file = conversationFile(dir, id);
  if (!file) return { ok: false, reason: "invalid conversation id" };
  const raw = await readRecords(file);
  if (!raw.exists) return { ok: false, reason: "no such conversation" };
  if (raw.error) return { ok: false, reason: raw.error };

  const [header, ...events] = raw.records;
  if (!header || !SUPPORTED_CONVERSATION_VERSIONS.includes(header.conversationSchemaVersion)) {
    const version = header?.conversationSchemaVersion;
    return {
      ok: false,
      reason:
        typeof version === "number" && version > CONVERSATION_SCHEMA_VERSION
          ? `conversation was written by schema v${version}; this client speaks v${CONVERSATION_SCHEMA_VERSION} and refuses to reinterpret it`
          : "conversation file has no valid header",
    };
  }
  return {
    ok: true,
    // v1 headers predate systemPrompt; consumers see the honest null rather
    // than each inventing its own absent-field handling.
    header: { ...header, systemPrompt: header.systemPrompt ?? null },
    events: events.filter((e) => validateEvent(e).ok),
    invalidEvents: events.filter((e) => !validateEvent(e).ok).length,
    tornTail: raw.tornTail,
    invalidLines: raw.invalidLines,
  };
}

/**
 * List conversations — ids and metadata, NO PROSE. The shape here is the
 * privacy boundary for the list surface: nothing in it can quote a message.
 */
export async function listConversations(dir) {
  const base = path.resolve(dir, CONVERSATIONS_DIR);
  let names;
  try {
    names = await fsp.readdir(base);
  } catch (err) {
    if (err.code === "ENOENT") return { ok: true, conversations: [] };
    return { ok: false, reason: String(err.message).slice(0, 120) };
  }

  const conversations = [];
  for (const name of names) {
    if (!name.endsWith(".jsonl")) continue;
    const id = name.slice(0, -".jsonl".length);
    if (!validConversationId(id)) continue;
    const read = await readConversation(dir, id);
    if (!read.ok) {
      conversations.push({ id, unreadable: true, reason: read.reason });
      continue;
    }
    conversations.push({
      id,
      createdAt: read.header.createdAt,
      model: read.header.model,
      messageCount: read.events.length,
      lastAt: read.events.length ? read.events[read.events.length - 1].at : read.header.createdAt,
    });
  }
  conversations.sort((a, b) => String(b.lastAt ?? "").localeCompare(String(a.lastAt ?? "")));
  return { ok: true, conversations };
}

/**
 * Delete one conversation. The package's second deletion, under the same
 * containment discipline as the first: the target is derivable only from a
 * pattern-validated id inside the conversations directory, and the associated
 * measurement records are deliberately NOT deleted — counters carry no prose,
 * and measurement history surviving a deleted conversation is the design
 * (§4a; the records' conversationId then refers to nothing, which is fine).
 */
export async function deleteConversation(dir, id) {
  const file = conversationFile(dir, id);
  if (!file) return { ok: false, reason: "invalid conversation id" };
  try {
    await fsp.access(file);
  } catch {
    return { ok: false, reason: "no such conversation" };
  }
  await fsp.rm(file, { force: true });
  return { ok: true };
}
